language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls
# command to run tests
script:
  cd tests && coverage run --source="../moira/" --omit="../moira/graphite/*,../moira/metrics/*" $(which trial) functional

after_success:
  coveralls

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/9992cd0d36a6ba9bb40b
    on_success: change
    on_failure: always
    on_start: never
